### ISSUE TITLE
Warning: call_user_func_array() expects parameter 1

### ISSUE THREAD

**Issue by fezguy** [Dev49net/wp-first-letter-avatar#2]
Hey Daniel,

This plugin seems to work great, my only concern is when I enable it I get the following warning on the dash on top as well as the main site on the bottom.

Warning: call_user_func_array() expects parameter 1 to be a valid callback, first array member is not a valid class name or object in /home/.../.../wp-includes/plugin.php on line 213

it also seems like the Round avatars option doesn't do anything.

Any help would be appreciated.

Cheers,
Fez

**Comment by Dev49net** [comment]
That's unusual. Are you sure you have the latest version? Maybe try downloading it from WordPress plugin directory instead? The round avatars not working is another weird thing. What it does, is it adds CSS class to all avatars, so maybe you don't have all plugin files?

P.S. Just updated the plugin with couple of small fixes, maybe it will help you.

**Comment by fezguy** [comment]
it's odd it wont go away and the round won't show up. I see the CSS you're referring to: "wp-first-letter-avatar-master/css/style.css" but it's marked as (inactive).

I also see this in the config: "    

public function wpfla_round_avatars_render(){

```
    ?>
    <input type='checkbox' name='wpfla_settings[wpfla_round_avatars]' <?php checked( $this->wpfla_options['wpfla_round_avatars'], 1 ); ?> value='1' />
<?php

} 
```

"

but still not doing anything. I just downloaded the new version 1.2.4 and installed it manually and also through the WP installer and same thing...

**Comment by Dev49net** [comment]
Hi there,
Thanks for the reply.
I am sure there is a conflict somewhere between WP First Letter Avatar and some of your other plugins (or maybe theme?). I am more than willing to fix this issue, but we have to get to the bottom of this problem so that we can find out what causes the problem. Can you tell me what plugins and what theme are you using? Do you think you could disable all your plugins (except for WP FIrst Letter Avatar) and check if the problem is gone? If it helps, start enabling other plugins until the problem happens again. That way we will be able to find out where exactly the problem happens.

**Comment by Dev49net** [comment]
Hi! 
Turns out you were not the only who had this problem. I just updated the plugin, please see if it works for you. The warning should no longer be displayed.
About the round avatars - the CSS class must be overwritten somewhere, maybe by your theme or other plugin. Please check it with developer console in any of the modern browsers to see what exactly is happening there. CSS class .wpfla.round-avatars class should be added the the avatar (with border-radius: 50%).
Thank you for your help. If the problem occurs again or you find another one, please feel free to report. 

Thanks,
Daniel
